<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/10/20 14:48:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=siwapp',
  'username' => 'siwapp',
  'password' => 'wappis',
  'name' => 'doctrine',
)),);
