<?php
// auto-generated by sfViewConfigHandler
// date: 2015/10/20 14:48:40
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'ajaxGetCountriesSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'step1Success')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'ajaxGetCountriesSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == '' ? false : ''.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'siwapp - Installer', false, false);

  $response->addStylesheet('tripoli/tripoli', '', array (  'media' => 'all',));
  $response->addStylesheet('tripoli/tripoli.ie.css', '', array (  'media' => 'all',  'condition' => 'ie',));
  $response->addStylesheet('siwapp/layout', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/typography', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/buttons', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/theme', '', array ());
  $response->addStylesheet('siwapp/controls', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/print', '', array (  'media' => 'print',));
  $response->addStylesheet('ui-orange/ui.all.css', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/installer', '', array (  'media' => 'all',));
  $response->addJavascript('/sfJqueryReloadedPlugin/js/jquery-1.3.2.min.js', '', array ());
}
else if ($templateName.$this->viewName == 'step1Success')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'siwapp - Installer', false, false);

  $response->addStylesheet('tripoli/tripoli', '', array (  'media' => 'all',));
  $response->addStylesheet('tripoli/tripoli.ie.css', '', array (  'media' => 'all',  'condition' => 'ie',));
  $response->addStylesheet('siwapp/layout', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/typography', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/buttons', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/theme', '', array ());
  $response->addStylesheet('siwapp/controls', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/print', '', array (  'media' => 'print',));
  $response->addStylesheet('ui-orange/ui.all.css', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/installer', '', array (  'media' => 'all',));
  $response->addJavascript('/sfJqueryReloadedPlugin/js/jquery-1.3.2.min.js', '', array ());
  $response->addJavascript('siwapp/lang.selector.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'siwapp - Installer', false, false);

  $response->addStylesheet('tripoli/tripoli', '', array (  'media' => 'all',));
  $response->addStylesheet('tripoli/tripoli.ie.css', '', array (  'media' => 'all',  'condition' => 'ie',));
  $response->addStylesheet('siwapp/layout', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/typography', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/buttons', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/theme', '', array ());
  $response->addStylesheet('siwapp/controls', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/print', '', array (  'media' => 'print',));
  $response->addStylesheet('ui-orange/ui.all.css', '', array (  'media' => 'all',));
  $response->addStylesheet('siwapp/installer', '', array (  'media' => 'all',));
  $response->addJavascript('/sfJqueryReloadedPlugin/js/jquery-1.3.2.min.js', '', array ());
}

